version: '3'
services:
  db:
    image: mysql:latest
    command: --authentication_policy=mysql_native_password
    env_file:
      - database.env
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  backend:
    build:
      context: /backend
      dockerfile: /backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"